name: gradients
wallpapers:
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: bkg3_bkg5.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: flamingo_peach.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: magenta_blue.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: magenta_pink.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: red_pink.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: green_bkg5.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: red_peach.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: red_bkg5.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: cyan_bkg5.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: flamingo_bkg1.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: blue_bkg5.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: peach_bkg5.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: bkg1_bkg5.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: flamingo_bkg5.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: blue_green.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: flamingo_yellow.png
    modified: false
