name: solids
wallpapers:
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: peach.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: gray.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: yellow.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: bkg3.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: flamingo.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: bkg2.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: pink.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: blue.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: bkg1.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: bkg5.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: bkg4.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: green.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: cyan.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: magenta.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: white.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: red.png
    modified: false
