name: flatppuccin
wallpapers:
  - author_name: AdalZanabria
    author_url: https://github.com/AdalZanabria
    image_url: flatppuccin_4k_macchiato_inverted.png
    modified: false
  - author_name: AdalZanabria
    author_url: https://github.com/AdalZanabria
    image_url: flatppuccin_4k_macchiato.png
    modified: false
