name: waves
wallpapers:
  - author_name: elkrien
    author_url: https://github.com/elkrien
    image_url: cat-waves.png
    modified: true
  - author_name: elkrien
    author_url: https://github.com/elkrien
    image_url: cat-blue-eye.png
    modified: true
