#!/bin/sh

xset s off
xset -dpms
xset r rate 584 69
xsetroot -def &

$HOME/.config/polybar/launch.sh &
sxhkd &
redshift -l 0.01:-99.0 -g 0.9 -t 5200:3500 -r randr &
hsetroot -fill .config/wallpaper/covers.png &
setxkbmap -layout br &
xrdb -load .Xresources &
xrandr --output DP-0 --primary --mode 1920x1080 --rate 165.00 --output HDMI-0 --mode 2560x1080 --rate 74.99 --right-of DP-0

xsetroot -cursor_name left_ptr &
picom &

xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

bspc config top_padding 	      1
bspc config bottom_padding 	    1
bspc config left_padding 	      1
bspc config right_padding 	    1 
bspc config border_width        0
bspc config window_gap          5

bspc monitor -d 1 2 3 4 5

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_focus   false
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true

bspc config focused_border_color  "#FFFFFF"
bspc config normal_border_color   "#272727"
bspc config presel_feedback_color "#FF0000"

#bspc desktop ^1 -l monocle
bspc rule -a TelegramDesktop desktop=^3
# bspc rule -a Brave desktop=^2 state=full
bspc rule -a Discord desktop=^4 state=floating
bspc rule -a Anki desktop=^5
bspc rule -a Sxiv state=floating follow=on
bspc rule -a MPlayer state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a zathura state=tiled follow=on
bspc rule -a wezterm state=floating

bspc config presel_feedback_color \#aaaaaa

notify-send "Notification" "Bspwmrc Loaded"

