#!/bin/sh

xset s off
xset -dpms
xset r rate 484 69
xsetroot -def &

$HOME/.config/bspwm/themes/onedark/polybar/launch.sh &
sxhkd &
parcellite &
setxkbmap -option caps:escape
redshift -l 0.01:-99.0 -g 0.8 -t 5200:5200 -r randr &
# hsetroot -fill .wallpapers/mechanical/macchiato.png &
nitrogen --set-zoom-fill workspaces/tmp/Configs/Wallpapers/RosePine/astronaut_fields.jpg
xrandr --output DP-1 --mode 1920x1080 --rate 120.00
# xrandr --output DP-1 --mode 2560x1080 --rate 74.99
xrdb -load .Xresources &
# xrandr --output DP-4 --primary --mode 1920x1080 --rate 165.00 --output HDMI-0 --mode 2560x1080 --rate 74.99 --right-of DP-4 --rotate right

xsetroot -cursor_name left_ptr &
picom &

# xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'

# bspc config top_padding 	      1
bspc config bottom_padding 1
bspc config left_padding 1
bspc config right_padding 1
bspc config border_width 2
bspc config window_gap 5

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled true

bspc config focused_border_color "#24283b"
bspc config normal_border_color "#272727"
bspc config presel_feedback_color "#FF0000"

#bspc desktop ^1 -l monocle
bspc rule -a TelegramDesktop desktop=^3
# bspc rule -a Brave desktop=^2 state=full
bspc rule -a Discord desktop=^4 state=floating
bspc rule -a Anki desktop=^5
bspc rule -a Calculator state=floating
bspc rule -a Sxiv state=floating follow=on
bspc rule -a MPlayer state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a zathura state=tiled follow=on
bspc rule -a wezterm state=floating

bspc config presel_feedback_color \#aaaaaa

notify-send "Notification" "Bspwmrc Loaded"
