#!/bin/sh

sxhkd &
polybar mybar &
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
bspc config top_padding 	      1
bspc config bottom_padding 	    1
bspc config left_padding 	      1
bspc config right_padding 	    1 
bspc config border_width        1 
bspc config window_gap          4

bspc monitor -d one two three four five six seven

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_focus   false
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true

bspc config focused_border_color  "#FFFFFF"
bspc config normal_border_color   "#272727"
bspc config presel_feedback_color "#FF0000"

#bspc desktop ^1 -l monocle
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Chromium desktop=^2
bspc rule -a Anki desktop=^5
bspc rule -a Sxiv state=floating follow=on
bspc rule -a mplayer state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a zathura state=tiled follow=on

bspc config presel_feedback_color \#aaaaaa

notify-send "Notification" "Bspwmrc Loaded"

