#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Run ncmpcpp with alternate config

# bspwm directory
DIR="$HOME/.config/bspwm"

alacritty --class 'Music,Music' \
  -o window.dimensions.columns=105 window.dimensions.lines=22 \
  -e ~/.ncmpcpp/scripts/ncmpcpp-art
