name: minimalistic
wallpapers:
  - author_name: BlueFalconHD
    author_url: https://github.com/BlueFalconHD
    image_url: hashtags-new.png
    modified: false
  - author_name: BlueFalconHD
    author_url: https://github.com/BlueFalconHD
    image_url: list-horizontal.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: black5_unicat.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: sky-cat.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: green-cat.png
    modified: false
  - author_name: elkrien
    author_url: https://github.com/elkrien
    image_url: tetris.png
    modified: false
  - author_name: BlueFalconHD
    author_url: https://github.com/BlueFalconHD
    image_url: list-aligned-right.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: teal-cat.png
    modified: false
  - author_name: BlueFalconHD
    author_url: https://github.com/BlueFalconHD
    image_url: cats.png
    modified: false
  - author_name: DakshG07
    author_url: https://github.com/DakshG07
    image_url: gradient-synth-cat.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: yellow-cat.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: blue_unicat.png
    modified: false
  - author_name: DonutDev
    author_url: https://github.com/DonutDev
    image_url: peach-cat.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: flamingo-cat.png
    modified: false
  - author_name: elkrien
    author_url: https://github.com/elkrien
    image_url: romb.png
    modified: false
  - author_name: elkrien
    author_url: https://github.com/elkrien
    image_url: sports.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: flamingo_unicat.png
    modified: false
  - author_name: DonutDev
    author_url: https://github.com/DonutDev
    image_url: red-cat.png
    modified: false
  - author_name: Victor Tennekes
    author_url: https://github.com/VictorTennekes
    image_url: catppuccin_triangle.png
    modified: false
  - author_name: elkrien
    author_url: https://github.com/elkrien
    image_url: buttons.png
    modified: false
  - author_name: DonutDev
    author_url: https://github.com/DonutDev
    image_url: dark-cat-rosewater.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: rosewater-cat.png
    modified: false
  - author_name: elkrien
    author_url: https://github.com/elkrien
    image_url: hearts.png
    modified: false
  - author_name: BlueFalconHD
    author_url: https://github.com/BlueFalconHD
    image_url: list-aligned-left.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: teal_unicat.png
    modified: false
  - author_name: DonutDev
    author_url: https://github.com/DonutDev
    image_url: maroon-cat.png
    modified: false
  - author_name: DonutDev
    author_url: https://github.com/DonutDev
    image_url: pink-cat.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: unicat.png
    modified: false
  - author_name: DonutDev
    author_url: https://github.com/DonutDev
    image_url: dark-cat.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: pink_unicat.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: peach_unicat.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: darker_unicat.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: blue-cat.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: red_unicat.png
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: magenta-cat.png
    modified: false
  - author_name: elkrien
    author_url: https://github.com/elkrien
    image_url: hashtags-black.png
    modified: false
  - author_name: andreasgrafen
    author_url: https://github.com/andreasgrafen
    image_url: heart.jpg
    modified: false
  - author_name: Gingeh
    author_url: https://github.com/Gingeh
    image_url: lavender-cat.png
    modified: false
  - author_name: rubyowo
    author_url: https://github.com/rubyowo
    image_url: mauve-cat.png
    modified: false
  - author_name: rubyowo
    author_url: https://github.com/rubyowo
    image_url: mauve_unicat.png
    modified: false
  - author_name: InvitedToHell
    author_url: https://github.com/InvitedToHell
    image_url: cut_rainbow.png
    modified: false
