name: landscapes
wallpapers:
  - author_name: Michal Kváč
    author_url: https://kvacm.artstation.com/
    image_url: https://cdnb.artstation.com/p/assets/images/images/023/810/475/large/michal-kvac-torii-rox-small.jpg?1580406414
    modified: false
  - author_name: Guilherme Rossi
    author_url: https://www.pexels.com/@guiirossi/
    source_url: https://www.pexels.com/photo/lighted-suspension-bridge-during-nighttime-1755680/
    image_url: Bridge.jpg
    modified: true
  - author_name: BisBiswas
    author_url: https://www.deviantart.com/bisbiswas
    image_url: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b3be1dae-3caa-4d45-be6c-3de586ba95e2/ddfk819-970f1d4f-6da3-4ccf-8e3f-0264f5e607e6.jpg/v1/fill/w_1600,h_900,q_75,strp/under_the_night_sky_by_bisbiswas_ddfk819-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9OTAwIiwicGF0aCI6IlwvZlwvYjNiZTFkYWUtM2NhYS00ZDQ1LWJlNmMtM2RlNTg2YmE5NWUyXC9kZGZrODE5LTk3MGYxZDRmLTZkYTMtNGNjZi04ZTNmLTAyNjRmNWU2MDdlNi5qcGciLCJ3aWR0aCI6Ijw9MTYwMCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.j8jKTC775V1VR6sxzL7WwpCPAKsRUKPfyJy6VROOy68
    modified: false
  - author_name: byrotek
    author_url: https://www.deviantart.com/byrotek
    image_url: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/80a9d98d-327f-4bb2-b173-4298d710e51c/derkflv-9f975f3d-791f-4e16-8d9d-fb0a9e5e0554.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzgwYTlkOThkLTMyN2YtNGJiMi1iMTczLTQyOThkNzEwZTUxY1wvZGVya2Zsdi05Zjk3NWYzZC03OTFmLTRlMTYtOGQ5ZC1mYjBhOWU1ZTA1NTQucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.eEDVAlJGBqXo6OeZEORXWk1veGSHFL-ZTUMz43Jtr3Q
    modified: false
  - author_name: Zahidul
    author_url: https://dribbble.com/zahidvector
    image_url: https://cdn.dribbble.com/users/1171505/screenshots/4098256/attachments/939118/binarymine-dribbble-01.png
    modified: false
  - author_name: Louis Coyle
    author_url: https://louie.co.nz/
    image_url: https://cdn.dribbble.com/users/13449/screenshots/12078823/media/c6662b0de7365559f79d9eb6088d9527.png
    modified: false
  - author_name: Louis Coyle
    author_url: https://louie.co.nz/
    image_url: https://cdn.dribbble.com/users/13449/screenshots/12078823/downloads/the_valley.png
    modified: false
