name: patterns
wallpapers:
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: emojis.png
    modified: false
  - author_name: Pocco81
    author_url: https://github.com/Pocco81
    image_url: line_icons.png
    modified: false
